language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  provider: heroku
  app: mocha-api-starter
  api_key:
    secure: ZHqvcTlCUmy6hYi1ejgCjHzyyfbW5wqwdMGS8itaq5EK8G2QwTkRR8bQvZytx9D6JYvRr3MuRNVICeuMDTxmpYsksdQ4D7nzEeu7aLiYAw7EuOV7Ck1hGEuutJn+uUPhw2odLlsHEOkHNSERnz6KJTWCdAxxaPXWqfFVmuA5afIyGGievliGn/KfNxcIl6v7lhiR+A5m/Vs5lJ+UnmUBZiyP9uXGkX6eYUy2AANaX0VZO1IwktBlMUH+9BMLJKXSGOnezrbr9DDstbmBmBd7SH3Ib1ybptW42IFHxahEexGrL+8LZU3qSw68DEPmTSfAH+L5/JpiibV0ga/Ev3hretpmtpgcvDcsUizBbSH4Wz4yoyUn9acQHETtEZCl1CzYCDI5B7/cFfkm8luPm2SpOt21ndiIJ5M9L2fD9pKGgL0F0Oa8ryaUO457rzGG8b/AkchGOSPnw7BjCqKT2/O36BNlCf/6EWGp/SHqCxmjnyVgGGkIFPWRGkMxcxW1kgkrB/HwCw+R6VTriMiGTLjBHjzfUio1cqdc4S4kkGGwk8/ZODQknJksyqCqMQsdaazCErhH4665CjZ9ptb3kOkyYTwSdOAsHFfNtCrL35Nufr9wO5yLAH0LtP1g/XX0xsQ/WLLDumw60A3OM+/smaSx2Z0N6+Fpblx0/JE5A0nw/pI=
notifications:
  email: false
